# Generated by Django 5.2.5 on 2025-08-07 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
                ('category', models.CharField(choices=[('forward', 'Forward'), ('defense', 'Defense'), ('goalie', 'Goalie')], max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('height_inches', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_lbs', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100)),
                ('birth_country', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('shoots', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=5)),
                ('catches', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=5)),
                ('draft_year', models.PositiveIntegerField(blank=True, null=True)),
                ('draft_round', models.PositiveIntegerField(blank=True, null=True)),
                ('draft_pick', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_rookie', models.BooleanField(default=False)),
                ('nhl_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_players', to='teams.team')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.position')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('penalty_minutes', models.PositiveIntegerField(default=0)),
                ('power_play_goals', models.PositiveIntegerField(default=0)),
                ('power_play_assists', models.PositiveIntegerField(default=0)),
                ('power_play_points', models.PositiveIntegerField(default=0)),
                ('short_handed_goals', models.PositiveIntegerField(default=0)),
                ('short_handed_assists', models.PositiveIntegerField(default=0)),
                ('short_handed_points', models.PositiveIntegerField(default=0)),
                ('shots_on_goal', models.PositiveIntegerField(default=0)),
                ('shooting_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_on_ice_seconds', models.PositiveIntegerField(default=0)),
                ('average_time_on_ice_seconds', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('overtime_losses', models.PositiveIntegerField(default=0)),
                ('shutouts', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('shots_against', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('goals_against_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('save_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='teams.team')),
            ],
            options={
                'ordering': ['-season__start_date', '-points'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('is_current', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='teams.team')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
    ]
